# Operations Research Assignment 1 — Computational Demonstration

This notebook is a reproducible companion to the assignment repository. It runs the two custom implementations, checks the results independently with SciPy, and generates the Matplotlib figures used for the computational analysis.

**Models covered**
- Big-M Simplex for the reduced 9-food Stigler Diet Problem
- Vogel's Approximation Method (VAM) followed by MODI for the balanced transportation problem

The notebook does not replace the assignment algorithms. It provides a convenient way to reproduce and inspect their results from one place.


In [1]:
from pathlib import Path
import subprocess
import sys
import numpy as np

ROOT = Path.cwd()
print("Working directory:", ROOT)
print("Python:", sys.version.split()[0])


Working directory: /mnt/data/repo_upgrade
Python: 3.11.


## 1. Run the Big-M implementation


In [2]:
result = subprocess.run(
    [sys.executable, "big_m_stigler.py"],
    capture_output=True, text=True, check=True,
)
print(result.stdout)


Big-M Simplex — Stigler Diet Problem
------------------------------------------
Non-zero food expenditures per day:
Wheat Flour            $0.02951906
Beef Liver             $0.00189256
Cabbage                $0.01121444
Spinach                $0.00500766
Navy Beans             $0.06102856

Minimum daily cost = $0.10866228
Minimum annual cost = $39.6617

Nutrient check:
Calories               3.0000 (minimum 3)
Protein                147.4135 (minimum 70)
Calcium                  0.8000 (minimum 0.8)
Iron                     60.4669 (minimum 12)
Vitamin A                 5.0000 (minimum 5)
Vitamin B1                4.1204 (minimum 1.8)
Vitamin B2                2.7000 (minimum 2.7)
Niacin                   27.3160 (minimum 18)
Vitamin C                75.0000 (minimum 75)

Maximum artificial-variable value = 0.0


## 2. Run the VAM + MODI implementation


In [3]:
result = subprocess.run(
    [sys.executable, "transportation_vam_modi_final.py"],
    capture_output=True, text=True, check=True,
)
print(result.stdout)


VAM + MODI — Transportation Problem
-------------------------------------
Initial VAM allocation:
[[20  0 20  0]
 [ 0  0  0 30]
 [ 5 30  0 15]]
Initial VAM cost = 725

MODI iteration 0:
u = [0, -3, 0]
v = [14, 1, 6, 7]
Most negative reduced cost = -2
Entering cell = S3, D3
Theta = 5
New transportation cost = 715

MODI iteration 1:
u = [0, -5, -2]
v = [14, 3, 6, 9]
Minimum reduced cost among unoccupied cells = 2
All reduced costs are non-negative. Current solution is optimal.

Final shipment plan:
[[25  0 15  0]
 [ 0  0  0 30]
 [ 0 30  5 15]]
Minimum transportation cost = 715


## 3. Independent LP verification with SciPy


In [4]:
result = subprocess.run(
    [sys.executable, "verify_results.py"],
    capture_output=True, text=True, check=True,
)
print(result.stdout)


Independent verification using SciPy linprog
Stigler minimum daily cost : $0.10866228
Positive food variables    :
  Wheat Flour          $0.02951906
  Beef Liver           $0.00189256
  Cabbage              $0.01121444
  Spinach              $0.00500766
  Navy Beans           $0.06102856

Transportation minimum cost: 715
Optimal shipment plan:
[[25  0 15  0]
 [ 0  0  0 30]
 [ 0 30  5 15]]

Verification status: PASS


## 4. Regression tests


In [5]:
result = subprocess.run(
    [sys.executable, "test_cases.py"],
    capture_output=True, text=True, check=True,
)
print(result.stdout)


Big-M implementation : PASS
VAM + MODI           : PASS
All regression tests : PASS


## 5. Generate and display the result figures


In [6]:
result = subprocess.run(
    [sys.executable, "visualize_results.py"],
    capture_output=True, text=True, check=True,
)
print(result.stdout)


Created:
  outputs/stigler_diet.png
  outputs/stigler_diet.svg
  outputs/transportation_plan.png
  outputs/transportation_plan.svg


In [7]:
from IPython.display import display, Image

print("Stigler Diet result")
display(Image(filename="outputs/stigler_diet.png", width=760))

print("Transportation result")
display(Image(filename="outputs/transportation_plan.png", width=650))


Stigler Diet result


Transportation result


## 6. Final reproducibility summary

The expected checks are:

| Check | Expected result |
|---|---|
| Big-M minimum daily cost | **$0.10866228** |
| Big-M minimum annual cost | **$39.6617** |
| Maximum artificial-variable value | **0.0** |
| VAM initial transportation cost | **725** |
| MODI final transportation cost | **715** |
| Independent SciPy transportation cost | **715** |
| Regression tests | **PASS** |

To reproduce the notebook from a fresh clone:

```bash
pip install -r requirements.txt
jupyter notebook OR_Assignment_1_Demo.ipynb
```

The notebook intentionally calls the existing Python programs rather than duplicating their algorithms, so there is one source of truth for the implementations.
